### ISSUE TITLE
Add support for more exceptions

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/http-exception-transformer#1]
checkout the list of Http Exceptions / Codes and add an entry to the source file. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

How to work on this:
- Find an exception / httpCode that is not implemented yet (check sources file for info).
- Open an issue for it
- Send PR fixing that issue.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by harshil15999** [comment]
1.Currently only the error codes have been implemented?
2. Do we have to make the error codes using the generators provided?

**Comment by YashKumarVerma** [comment]
> 1.Currently only the error codes have been implemented?
> 2. Do we have to make the error codes using the generators provided?

the exception classes are being generated using a function written in the package. The only change that needs to be done is adding entries to the [sources](https://github.com/UniAuth/http-exception-transformer/blob/master/src/lib/source.ts) file

**Comment by YashKumarVerma** [comment]
> Can I work on this issue under GSSoC'21? Kindly assign it to me.

How to work on this:

Find an exception / httpCode that is not implemented yet (check sources file for info).
Open an issue for it
Send PR fixing that issue.
