### ISSUE TITLE
Colour Coding the exception in the command line

### ISSUE THREAD

**Issue by harshil15999** [UniAuth/http-exception-transformer#2]
**Is your feature request related to a problem? Please describe.**
Whenever we throw Exceptions it comes in black and white in the terminal. 

**Describe the solution you'd like**
It would be easier and faster if each of the exceptions come with a color code associated with it

**Comment by YashKumarVerma** [comment]
since this is a middleware, it should ideally not inject more libraries into the application that uses it. Therefore we must avoid doing the same. 

What can be done is allowing the user to define a function that runs every time when an exception is thrown, that'd be a nice feature.

**Comment by harshil15999** [comment]
1. It would be optional to color code it 
2. is this the kind of feature you looking for 
[
error:"",
message:""
function_to_run:""
]

**Comment by YashKumarVerma** [comment]
> 1. It would be optional to color code it
> 2. is this the kind of feature you looking for
>    [
>    error:"",
>    message:""
>    function_to_run:""
>    ]

yes

**Comment by harshil15999** [comment]
For point 1?

**Comment by harshil15999** [comment]
If we are adding function to run suitable changes would have to be made in the **generators** folder to right

**Comment by YashKumarVerma** [comment]
> If we are adding function to run suitable changes would have to be made in the **generators** folder to right

yes

**Comment by harshil15999** [comment]
PLEASE REFER TO #6
