### ISSUE TITLE
Run a custom user defined function for any error 

### ISSUE THREAD

**Issue by harshil15999** [UniAuth/http-exception-transformer#6]
**Is your feature request related to a problem? Please describe.**
Allow user to define a function before on encountering an exception 

**Describe the solution you'd like**
 this the kind of feature you looking for
[
error:"",
message:""
function_to_run:""
]

**Comment by harshil15999** [comment]
Does function have to run before or after throwing the exception or  it would not matter!

**Comment by YashKumarVerma** [comment]
> Does function have to run before or after throwing the exception or it would not matter!

any one works fine

**Comment by harshil15999** [comment]
Please assign

**Comment by YashKumarVerma** [comment]
why do we need error function when it's already implemented ?:(

**Comment by harshil15999** [comment]
The functions which have to be run before throwing the error

**Comment by YashKumarVerma** [comment]
yes but why do we need a separate folder for the error functions? 
From what I understand, since all the exceptions need this feature, we'd need to edit only the parent class

**Comment by harshil15999** [comment]
So in the generator code you want to be able to define a function! 
2) what is the programming concept called in the generators.ts which youhave used to create all other code !
