### ISSUE TITLE
Forbidden Exception sening 200 status code

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/http-exception-transformer#9]
**Describe the bug**
[check title]

**To Reproduce**
1. Throw a forbidden exception
2. Check status code
3. Status code comes to be 200

**Expected behavior**
- the status code should be 403

![https://i.imgur.com/ox7Vvfp.png](https://i.imgur.com/ox7Vvfp.png)

**Comment by harshil15999** [comment]
Is this happening with all the newly added error codes?

**Comment by YashKumarVerma** [comment]
not sure, please check.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by YashKumarVerma** [comment]
@AshuKV can you check if this bug is there for other exceptions as well? Try it out for NotFoundException and let us know.

**Comment by harshil15999** [comment]
@AshuKV what was the result?

**Comment by YashKumarVerma** [comment]
This has been fixed.
